window.__EEA_EN__ = {
  "site.name": "Elliniki Engineering Academy",
  "site.short": "EEA",
  "site.tagline": "Engineering Excellence in the Heart of Greece",

  "top.phone": "+30 210 36543069",
  "top.address": "Κρήτης 45, Peania 190 02, Greece",
  "top.email": "info@elliniki-eng.gr",
  "top.library": "Library",
  "top.career": "Careers",
  "top.alumni": "Alumni",

  "nav.home": "Home",
  "nav.about": "About",
  "nav.about.intro": "Introduction",
  "nav.about.history": "Our History",
  "nav.about.mission": "Mission & Values",
  "nav.about.leadership": "Leadership",
  "nav.about.campus": "Campus & Facilities",
  "nav.academics": "Academics",
  "nav.academics.programs": "Programmes",
  "nav.academics.faculty": "Departments",
  "nav.academics.calendar": "Academic Calendar",
  "nav.academics.library": "Library",
  "nav.admissions": "Admissions",
  "nav.admissions.apply": "How to Apply",
  "nav.admissions.requirements": "Requirements",
  "nav.admissions.tuition": "Tuition & Fees",
  "nav.admissions.international": "International Students",
  "nav.research": "Research",
  "nav.life": "Campus Life",
  "nav.news": "News & Events",
  "nav.news.list": "Latest News",
  "nav.news.events": "Upcoming Events",
  "nav.contact": "Contact",
  "nav.portal": "Portal Login",

  "hero.eyebrow": "Founded November 2025 · Peania, Attica",
  "hero.title": "Shaping Tomorrow's Engineers Where Ancient Wisdom Meets Modern Innovation",
  "hero.subtitle": "Elliniki Engineering Academy is a private institution dedicated to advancing engineering education and applied research in the cradle of Western civilization.",
  "hero.cta1": "Explore Programmes",
  "hero.cta2": "Apply for Autumn 2026",

  "stats.students": "Founding Students",
  "stats.faculty": "Faculty Members",
  "stats.programs": "Degree Programmes",
  "stats.partners": "Industry Partners",

  "about.eyebrow": "A New Chapter in Greek Engineering",
  "about.title": "Where Innovation Meets a 3,000-Year Tradition of Knowledge",
  "about.p1": "Established in November 2025 in the historic Peania district of Attica, Elliniki Engineering Academy is one of Greece's newest private institutions of higher education. Our founders — a coalition of Greek engineering veterans, returning diaspora academics, and European industrial partners — set out to build a school that combines the rigor of European engineering tradition with the agility of a modern technology institute.",
  "about.p2": "Though we welcomed our first cohort only six months ago, our 12,000 m² Peania campus, brand-new laboratories, and partnerships across the Athens technology corridor give our 286 founding students a head start few institutions can match.",
  "about.f1": "EU-aligned curriculum benchmarked against TU Delft, ETH and NTUA standards",
  "about.f2": "Bilingual instruction in Greek and English from day one",
  "about.f3": "Student-to-faculty ratio of 8:1 — among the lowest in Greece",
  "about.f4": "Located 25 minutes from Athens International Airport",
  "about.more": "Learn More About EEA",

  "programs.eyebrow": "Academic Programmes",
  "programs.title": "Engineering Disciplines for the Decade Ahead",
  "programs.subtitle": "Our six founding departments offer rigorous undergraduate and master's programmes designed in close collaboration with European industry partners.",

  "prog.cs.title": "Computer & Software Engineering",
  "prog.cs.desc": "From algorithms to AI systems engineering — train under faculty drawn from ETH Zürich, NTUA and Athens-based deep-tech founders.",
  "prog.civil.title": "Civil & Structural Engineering",
  "prog.civil.desc": "Design the infrastructure of a seismic country. Includes a dedicated earthquake-resilience track and a year-long site practicum.",
  "prog.mech.title": "Mechanical Engineering",
  "prog.mech.desc": "Hands-on labs in robotics, additive manufacturing and propulsion — including access to our new 800 m² Mechatronics Hall.",
  "prog.elec.title": "Electrical & Energy Systems",
  "prog.elec.desc": "From smart grids to photovoltaics. Greece is rebuilding its energy backbone, and our graduates are being trained to lead it.",
  "prog.env.title": "Environmental & Marine Engineering",
  "prog.env.desc": "Coastal protection, desalination, blue-economy systems. A discipline shaped by the Aegean itself.",
  "prog.arch.title": "Architecture & Built Heritage",
  "prog.arch.desc": "A unique programme blending modern structural design with the conservation of Mediterranean architectural heritage.",
  "prog.viewall": "View all programmes",

  "news.eyebrow": "News & Announcements",
  "news.title": "What's Happening at EEA",
  "news.viewall": "Read all news",

  "events.eyebrow": "Upcoming",
  "events.title": "Events Calendar",
  "events.viewall": "Full calendar",
  "events.details": "Details",

  "cta.title": "Applications for Autumn 2026 Are Now Open",
  "cta.desc": "Join one of Greece's most ambitious new engineering programmes. Early-decision deadline: 30 June 2026.",
  "cta.btn": "Start Your Application",

  "footer.about": "Elliniki Engineering Academy is a private engineering institute established in 2025 in Peania, Attica. Authorised to deliver licensed undergraduate programmes via affiliated European universities.",
  "footer.quick": "Quick Links",
  "footer.programs": "Programmes",
  "footer.contact": "Get in Touch",
  "footer.copyright": "© 2026 Elliniki Engineering Academy. All rights reserved.",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms of Use",
  "footer.accessibility": "Accessibility",
  "footer.sitemap": "Sitemap",

  "page.about.title": "About the Academy",
  "page.about.sub": "A new institution rooted in an ancient tradition of inquiry.",
  "page.academics.title": "Academics",
  "page.academics.sub": "Six disciplines, one rigorous European engineering curriculum.",
  "page.admissions.title": "Admissions",
  "page.admissions.sub": "Apply to one of Greece's most ambitious new engineering programmes.",
  "page.research.title": "Research",
  "page.research.sub": "Applied research that serves Greece's industrial renaissance.",
  "page.life.title": "Campus Life",
  "page.life.sub": "Live, learn, and build in the heart of ancient Attica.",
  "page.news.title": "News & Stories",
  "page.news.sub": "Updates from across the Academy.",
  "page.events.title": "Events",
  "page.events.sub": "Lectures, symposia, open days and community gatherings.",
  "page.contact.title": "Contact Us",
  "page.contact.sub": "We'd love to hear from prospective students, partners and visitors.",
  "page.portal.title": "Portal Login",
  "page.portal.sub": "Sign in to access your student, faculty, or staff account.",

  "portal.student": "Student Portal",
  "portal.faculty": "Faculty & Staff Portal",
  "portal.student.sub": "Sign in with your EEA student credentials",
  "portal.faculty.sub": "Sign in with your faculty or staff credentials",
  "portal.username": "Username or Student ID",
  "portal.usernamefac": "Username or Staff ID",
  "portal.password": "Password",
  "portal.remember": "Remember me",
  "portal.forgot": "Forgot password?",
  "portal.signin": "Sign In",
  "portal.error": "Invalid username or password. Please verify your credentials and try again.",
  "portal.notice": "By signing in, you agree to abide by the EEA Acceptable Use Policy. Unauthorised access is prohibited.",
  "portal.help": "Need help? Contact IT Support at it-support@elliniki-eng.gr or +30 210 36543069 ext. 200.",
  "portal.first": "First-time user? Activate your account",
  "portal.switch": "Not a student? ",
  "portal.switchfac": "Not faculty? ",

  "about.intro.h2": "Introduction",
  "about.intro.p1": "Elliniki Engineering Academy (EEA) is a private engineering institute located in Peania, Attica, just east of Athens. Founded in November 2025, EEA was established to address a clear and pressing gap in Greek higher education: the need for an agile, industry-aligned, English-and-Greek-instruction engineering school capable of training the talent required by Greece's ongoing energy transition, digital transformation, and infrastructure renewal.",
  "about.intro.p2": "EEA operates under the framework of Law 4957/2022 (the law liberalising private higher education in Greece) and delivers degree programmes through structured academic affiliations with established European universities — a model already used by leading colleges in the Athens area. Our curricula are externally examined and our degrees are issued by partner universities while teaching, research and student support take place on our Peania campus.",
  "about.history.h2": "Our History",
  "about.history.p1": "The idea for EEA emerged in 2023, when a group of Greek engineering professionals working abroad — at Siemens Mobility, Arup, Imperial College and ETH Zürich — began informal conversations about the long-term skills bottleneck facing Greek industry. A formal foundation, the <em>Idryma Elliniki Akadimia Mihanikis</em>, was registered in early 2024, securing initial endowment from a coalition of family offices, the Stavros Niarchos-affiliated Athens Engineering Trust, and three European industrial partners.",
  "about.history.p2": "Site selection for the campus began in mid-2024, and the property at Κρήτης 45 in Peania — formerly a Hellenic Aerospace Industry research wing — was acquired in late 2024 and refurbished over the following ten months. EEA enrolled its founding class of 286 undergraduates in November 2025.",
  "about.mission.h2": "Mission &amp; Values",
  "about.mission.p1": "EEA's mission is to deliver engineering education that is rigorous, ethical and rooted in the realities of contemporary Greece — a country that sits at the crossroads of the Mediterranean energy transition, growing demand for infrastructure resilience, and an expanding deep-tech ecosystem around Athens.",
  "about.mission.h3": "Our Core Values",
  "about.mission.v1": "<strong>Άριστεία (Aristeía) — Excellence.</strong> We hold ourselves and our students to the highest international engineering standards.",
  "about.mission.v2": "<strong>Φιλομάθεια (Filomátheia) — Love of Learning.</strong> We cultivate intellectual curiosity as a discipline, not a slogan.",
  "about.mission.v3": "<strong>Ευθύνη (Efthýni) — Responsibility.</strong> Engineering is a public profession. We educate engineers accountable to the societies they build for.",
  "about.mission.v4": "<strong>Σύνθεση (Sýnthesi) — Synthesis.</strong> Greek thought has always prized the union of theoria and praxis. Our curriculum reflects that.",
  "about.lead.h2": "Leadership",
  "about.lead.p1": "EEA is governed by a Board of Trustees and led by an Academic Senate composed of department deans. Day-to-day operations are managed by the Office of the Rector.",
  "about.lead.r1.title": "Founding Rector",
  "about.lead.r1.bio": "Previously Vice-Provost, NTUA. PhD MIT.",
  "about.lead.r2.title": "Vice-Rector, Academic Affairs",
  "about.lead.r2.bio": "20 years at TU Delft. Returning diaspora academic.",
  "about.lead.r3.title": "Dean, Civil &amp; Structural Eng.",
  "about.lead.r3.bio": "Former chief engineer, Athens Metro extensions.",
  "about.lead.r4.title": "Dean, Computer &amp; Software Eng.",
  "about.lead.r4.bio": "Ex-Google Zürich. PhD EPFL.",
  "about.lead.r5.title": "Dean, Mechanical Eng.",
  "about.lead.r5.bio": "Co-founder, two Athens robotics start-ups.",
  "about.lead.r6.title": "Dean, Electrical &amp; Energy",
  "about.lead.r6.bio": "Former lead, HEDNO grid modernisation.",
  "about.lead.r7.title": "Dean, Environmental &amp; Marine",
  "about.lead.r7.bio": "20+ Aegean coastal engineering projects.",
  "about.lead.r8.title": "Dean, Architecture &amp; Heritage",
  "about.lead.r8.bio": "RIBA chartered. UNESCO heritage advisor.",
  "about.campus.h2": "Campus &amp; Facilities",
  "about.campus.p1": "Our 12,000 m² campus in Peania occupies a refurbished former research site of the Hellenic Aerospace Industry. The campus opened to students in November 2025 and is being expanded in phases. The current footprint includes:",
  "about.campus.b1": "Building A — Academic block with eight 80-seat lecture halls and twelve 30-seat tutorial rooms",
  "about.campus.b2": "Building B — The Mechatronics Hall (800 m²) housing robotics, additive manufacturing, and propulsion labs",
  "about.campus.b3": "Building C — Computer Science complex with five teaching labs and one 64-node compute cluster",
  "about.campus.b4": "Building D — Civil &amp; Structural laboratories, including a 200-tonne universal testing frame and a 4 m shake-table",
  "about.campus.b5": "The Onassis Library — 22,000 physical volumes plus access to 18 major academic databases",
  "about.campus.b6": "Sports facilities — outdoor 5-a-side football pitch, basketball court, and partnership access to Peania Municipal Pool",
  "about.campus.b7": "Student Centre — café, study lounges, prayer/quiet room, and the EEA Bookstore",
  "about.campus.p2": "A second phase of construction, scheduled for completion in autumn 2027, will add Building E (a 4,500 m² combined energy systems and marine engineering wing) and a dedicated 250-bed student residence.",
  "about.side.onpage": "On this page",
  "about.side.facts": "Quick Facts",
  "about.side.f1": "<strong>Founded:</strong> November 2025",
  "about.side.f2": "<strong>Type:</strong> Private, non-profit",
  "about.side.f3": "<strong>Location:</strong> Peania, Attica",
  "about.side.f4": "<strong>Campus size:</strong> 12,000 m²",
  "about.side.f5": "<strong>Students:</strong> 286 (founding class)",
  "about.side.f6": "<strong>Faculty:</strong> 38",
  "about.side.f7": "<strong>Departments:</strong> 6",
  "about.side.f8": "<strong>Instruction:</strong> Greek &amp; English",
  "about.side.apply": "Apply for 2026",
  "ac.structure.h2": "Programme Structure",
  "ac.structure.p1": "All EEA undergraduate engineering programmes are four-year (240 ECTS) Bachelor of Engineering (B.Eng) degrees, externally examined and validated by our European partner universities. Master's (M.Sc / M.Eng) programmes follow a one-and-a-half-year structure (90 ECTS) and a B.Arch / M.Arch track is offered in Architecture. Instruction is delivered in English for all engineering programmes, with parallel Greek-language tutorial support; the Architecture &amp; Heritage programme is offered bilingually.",
  "ac.undergrad.h2": "Undergraduate Programmes",
  "ac.cs.h3": "Computer &amp; Software Engineering (B.Eng)",
  "ac.cs.p1": "A four-year programme that combines a rigorous mathematical foundation with applied work in software systems, machine learning, and computer architecture. Year four is taken either as an Industrial Year (placed with one of our 24 partner companies) or as a Research Year inside an EEA lab.",
  "ac.cs.p2": "<strong>Core areas:</strong> Algorithms &amp; Data Structures · Operating Systems · Distributed Systems · Machine Learning · Software Engineering · Computer Networks · Information Security · Human-Computer Interaction · AI Systems Engineering.",
  "ac.cs.p3": "<strong>Capacity:</strong> 60 students per cohort · <strong>Tuition:</strong> €8,500 / year (Greek &amp; EU) · €11,800 / year (international).",
  "ac.civil.h3": "Civil &amp; Structural Engineering (B.Eng)",
  "ac.civil.p1": "Designed for a country shaped by seismic activity and a Mediterranean climate. The curriculum integrates structural analysis, geotechnics, and a dedicated final-year track in <em>Earthquake-Resilient Design</em>, taught in partnership with the Earthquake Planning &amp; Protection Organisation (OASP).",
  "ac.civil.p2": "<strong>Core areas:</strong> Structural Analysis · Reinforced Concrete &amp; Steel · Geotechnical Engineering · Hydraulic Engineering · Construction Materials · Earthquake Engineering · Transportation Infrastructure · Building Information Modelling (BIM).",
  "ac.civil.p3": "<strong>Capacity:</strong> 45 students per cohort · <strong>Tuition:</strong> €8,500 / €11,800.",
  "ac.mech.h3": "Mechanical Engineering (B.Eng)",
  "ac.mech.p1": "Hands-on from day one. EEA's flagship 800 m² Mechatronics Hall houses six KUKA collaborative robots, additive manufacturing equipment, a wind tunnel, and propulsion test cells. The programme follows the modern German <em>Maschinenbau</em> tradition adapted for industrial robotics and sustainable manufacturing.",
  "ac.mech.p2": "<strong>Core areas:</strong> Mechanics of Materials · Thermodynamics &amp; Heat Transfer · Fluid Mechanics · Control Systems · Robotics · CAD/CAM · Additive Manufacturing · Engineering Design.",
  "ac.mech.p3": "<strong>Capacity:</strong> 50 students per cohort · <strong>Tuition:</strong> €8,500 / €11,800.",
  "ac.elec.h3": "Electrical &amp; Energy Systems (B.Eng)",
  "ac.elec.p1": "Greece is rebuilding its energy backbone. This programme positions graduates at the centre of the transition — from photovoltaic plant design to smart-grid operations to electrical vehicle charging infrastructure.",
  "ac.elec.p2": "<strong>Core areas:</strong> Circuit Theory · Power Systems · Power Electronics · Renewable Energy Systems · Smart Grids · Control &amp; Automation · Electric Machines · Energy Markets &amp; Policy.",
  "ac.elec.p3": "<strong>Capacity:</strong> 45 students per cohort · <strong>Tuition:</strong> €8,500 / €11,800.",
  "ac.env.h3": "Environmental &amp; Marine Engineering (B.Eng)",
  "ac.env.p1": "Greece's 13,676 km coastline is its greatest natural asset and its largest engineering challenge. This programme combines water and coastal engineering with marine renewables and blue-economy systems.",
  "ac.env.p2": "<strong>Core areas:</strong> Environmental Chemistry · Hydrology · Coastal Engineering · Water Treatment &amp; Desalination · Air Quality · Marine Renewables · Climate Adaptation · Environmental Impact Assessment.",
  "ac.env.p3": "<strong>Capacity:</strong> 35 students per cohort · <strong>Tuition:</strong> €8,500 / €11,800.",
  "ac.arch.h3": "Architecture &amp; Built Heritage (B.Arch + M.Arch, 5 years)",
  "ac.arch.p1": "A five-year integrated programme (300 ECTS) that combines a contemporary architectural design education with the conservation of Mediterranean architectural heritage. Studio courses are taught bilingually in Greek and English. Year three includes a mandatory term at a partner heritage site.",
  "ac.arch.p2": "<strong>Core areas:</strong> Architectural Design · Construction &amp; Technology · History &amp; Theory · Structural Conservation · Urban Design · Sustainability · Digital Fabrication · Heritage Documentation.",
  "ac.arch.p3": "<strong>Capacity:</strong> 30 students per cohort · <strong>Tuition:</strong> €9,200 / €12,500.",
  "ac.masters.h2": "Master's Programmes",
  "ac.masters.p1": "EEA offers four 90-ECTS Master's programmes, each delivered over three semesters (12 months of taught coursework plus a six-month thesis project). All Master's programmes will admit their first cohort in autumn 2027.",
  "ac.masters.col1": "Programme",
  "ac.masters.col2": "Duration",
  "ac.masters.col3": "Language",
  "ac.masters.col4": "Tuition",
  "ac.masters.m1.name": "M.Sc in AI Systems Engineering",
  "ac.masters.m1.dur": "18 months",
  "ac.masters.m1.lang": "English",
  "ac.masters.m1.fee": "€11,500",
  "ac.masters.m2.name": "M.Eng in Earthquake Engineering",
  "ac.masters.m2.dur": "18 months",
  "ac.masters.m2.lang": "English",
  "ac.masters.m2.fee": "€11,500",
  "ac.masters.m3.name": "M.Sc in Renewable Energy &amp; Grid Integration",
  "ac.masters.m3.dur": "18 months",
  "ac.masters.m3.lang": "English",
  "ac.masters.m3.fee": "€11,500",
  "ac.masters.m4.name": "M.Sc in Coastal &amp; Marine Engineering",
  "ac.masters.m4.dur": "18 months",
  "ac.masters.m4.lang": "English",
  "ac.masters.m4.fee": "€11,500",
  "ac.dept.h2": "Departments",
  "ac.dept.p1": "Each of EEA's six departments is led by a Dean who reports to the Vice-Rector for Academic Affairs. Departments are responsible for curriculum design, faculty hiring, research direction, and student academic support.",
  "ac.dept.cs.h3": "Department of Computer Engineering",
  "ac.dept.cs.p": "Dean: Dr. Sofia Lekka · 8 faculty · 60 students",
  "ac.dept.page": "Department page",
  "ac.dept.civil.h3": "Department of Civil Engineering",
  "ac.dept.civil.p": "Dean: Prof. A. Papadopoulos · 7 faculty · 45 students",
  "ac.dept.mech.h3": "Department of Mechanical Engineering",
  "ac.dept.mech.p": "Dean: Prof. N. Mavrogiannis · 7 faculty · 50 students",
  "ac.dept.elec.h3": "Department of Electrical Engineering",
  "ac.dept.elec.p": "Dean: Dr. E. Kontou · 6 faculty · 45 students",
  "ac.dept.env.h3": "Dept. of Environmental Engineering",
  "ac.dept.env.p": "Dean: Prof. Y. Christoforou · 5 faculty · 35 students",
  "ac.dept.arch.h3": "Dept. of Architecture &amp; Heritage",
  "ac.dept.arch.p": "Dean: Dr. A. Petrakis · 5 faculty · 30 students",
  "ac.cal.h2": "Academic Calendar 2025/26 &amp; 2026/27",
  "ac.cal.col1": "Event",
  "ac.cal.col2": "Dates",
  "ac.cal.r1c1": "Winter Semester 2025/26 — Lectures",
  "ac.cal.r1c2": "10 Nov 2025 → 30 Jan 2026",
  "ac.cal.r2c1": "Winter Examinations",
  "ac.cal.r2c2": "02 Feb → 20 Feb 2026",
  "ac.cal.r3c1": "Spring Semester 2025/26 — Lectures",
  "ac.cal.r3c2": "02 Mar → 12 Jun 2026",
  "ac.cal.r4c1": "Spring Examinations",
  "ac.cal.r4c2": "15 Jun → 03 Jul 2026",
  "ac.cal.r5c1": "Summer Break",
  "ac.cal.r5c2": "04 Jul → 06 Sep 2026",
  "ac.cal.r6c1": "Resit Examinations",
  "ac.cal.r6c2": "07 Sep → 18 Sep 2026",
  "ac.cal.r7c1": "New Student Orientation 2026/27",
  "ac.cal.r7c2": "21 Sep → 25 Sep 2026",
  "ac.cal.r8c1": "Winter Semester 2026/27 — Lectures",
  "ac.cal.r8c2": "28 Sep 2026 → 22 Jan 2027",
  "ac.cal.r9c1": "Christmas Recess",
  "ac.cal.r9c2": "22 Dec 2026 → 06 Jan 2027",
  "ac.cal.r10c1": "Easter Recess (Orthodox)",
  "ac.cal.r10c2": "03 Apr → 16 Apr 2027",
  "ac.cal.holidays": "Holidays observed: 28 Oct (Ohi Day), 17 Nov (Polytechnic Day), 25 Mar (Independence), Orthodox Easter Friday &amp; Monday, 1 May (Labour Day), 15 Aug (Dormition).",
  "ac.side.programs": "Programmes",
  "ac.side.cs": "Computer Engineering",
  "ac.side.civil": "Civil Engineering",
  "ac.side.mech": "Mechanical Engineering",
  "ac.side.elec": "Electrical Engineering",
  "ac.side.env": "Environmental &amp; Marine",
  "ac.side.arch": "Architecture &amp; Heritage",
  "ac.side.masters": "Master's Programmes",
  "ac.side.resources": "Resources",
  "ac.side.calendar": "Academic Calendar",
  "ac.side.library": "Onassis Library",
  "ac.side.research": "Research Centres",
  "ac.side.apply": "Apply Now",
  "access.h1": "Accessibility Statement",
  "access.tagline": "Our commitment to making EEA accessible to everyone.",
  "access.intro": "Elliniki Engineering Academy is committed to making its services accessible to all members of the community, including people with disabilities. This statement applies to the eea.edu.gr website and to our Peania campus.",
  "access.web.h2": "This Website",
  "access.web.p1": "The EEA website is designed to substantially conform to the Web Content Accessibility Guidelines (WCAG) 2.1 at the AA level. Specific measures we have taken include:",
  "access.web.b1": "Sufficient text-background contrast across all main interface elements",
  "access.web.b2": "Semantic HTML structure with clear heading hierarchy",
  "access.web.b3": "Keyboard navigability of all interactive elements",
  "access.web.b4": "Descriptive alt-text on informative images",
  "access.web.b5": "Resizable text without breakage up to 200 %",
  "access.web.b6": "Captioning of all video content (when present) in Greek and English",
  "access.web.p2": "We are aware of the following limitations and are actively addressing them: the interactive embedded map and certain third-party PDF documents are not yet fully accessible. Accessible alternatives are available on request from <strong>access@eea.edu.gr</strong>.",
  "access.campus.h2": "Our Campus",
  "access.campus.p1": "The Peania campus is built to the post-2022 Greek accessibility code. Buildings A, B and C are step-free; lifts serve all upper floors. Accessible WCs are located on every floor. A wheelchair-accessible drop-off bay is at the main entrance, and four reserved accessible parking spaces are located in the visitor car park. The Onassis Library has two height-adjustable workstations and screen-reader software pre-installed.",
  "access.campus.p2": "The Mechatronics Hall has a small step at one entrance; a permanent ramp is scheduled for installation in summer 2026.",
  "access.report.h2": "Reporting an Issue",
  "access.report.p": "If you encounter an accessibility barrier on the website or on campus, please contact us at <strong>access@eea.edu.gr</strong> or +30 210 36543069 ext. 145. We aim to acknowledge within 2 working days and to respond substantively within 10 working days.",
  "alumni.bc": "Alumni",
  "alumni.h1": "The EEA Alumni Network",
  "alumni.tagline": "A network in formation — and one we will build together.",
  "alumni.day1.h2": "An Alumni Network on Day One",
  "alumni.day1.p1": "EEA is six months old. Our first cohort will not graduate until 2029. And yet — somewhat unusually for a new institution — EEA already has an alumni network of more than 240 members.",
  "alumni.day1.p2": "This is because, in 2024, EEA's founders launched a parallel programme called the <em>Founders' Alumni Programme</em> — open to graduates of <em>any</em> Greek or diaspora engineering institution who actively supported the establishment of EEA, by donating, mentoring, lecturing, or serving on a working group. Members of this network — engineers from NTUA, AUTh, EMP, Demokritos, but also from Imperial, MIT, ETH and TU Delft — form the seed of what will become a much wider EEA alumni community in the years ahead.",
  "alumni.what.h2": "What the Alumni Network Does",
  "alumni.what.b1": "Co-ordinates the EEA mentorship programme, pairing alumni mentors with current undergraduates",
  "alumni.what.b2": "Hosts the annual Alumni Symposium (next: 5–6 September 2026, on the Peania campus)",
  "alumni.what.b3": "Manages the alumni fund, which supports student scholarships and the Daedalus Society",
  "alumni.what.b4": "Maintains the EEA Engineering Speakers' Bureau — alumni who guest-lecture for EEA students",
  "alumni.what.b5": "Operates regional chapters in Athens, Thessaloniki, London and New York",
  "alumni.join.h2": "Join",
  "alumni.join.p": "The Founders' Alumni Programme is currently closed to new members; the wider EEA Alumni Network will open with our first graduating cohort in 2029. If you are an alumnus of another institution and wish to support EEA, please contact the Office of Development at <strong>development@eea.edu.gr</strong>.",
  "alumni.side.office": "Alumni Office",
  "alumni.side.involved": "Get Involved",
  "alumni.side.mentor": "Become a mentor",
  "alumni.side.lecture": "Guest-lecture",
  "alumni.side.scholar": "Support a scholarship",
  "alumni.side.chapter": "Regional chapters",
  "alumni.side.office.p": "Building A, Floor 1<br>\n                        +30 210 36543069 (ext. 140)<br>\n                        alumni@eea.edu.gr\n                    </p>\n                    Get Involved\n                    <ul>\n                        <li>Become a mentor</li>\n                        <li>Guest-lecture</li>\n                        <li>Support a scholarship</li>\n                        <li>Regional chapters</li>\n                    </ul>\n                </aside>",
  "life.peania.eyebrow": "Living in Peania",
  "life.peania.h2": "A Quiet Town on the Edge of Athens",
  "life.peania.p1": "Peania (Παιανία) is a town of around 16,000 residents in East Attica, traditionally known as the birthplace of the ancient Athenian orator Demosthenes. Today it sits at the intersection of the Athens technology corridor: the Athens International Airport is 8 km to the east, the Athens metro Line 3 terminus at Doukissis Plakentias is 6 km west, and the centre of Athens is 30 minutes away.",
  "life.peania.p2": "The town centre is small but lively — a handful of tavernas, three coffee shops on the main square, a Sunday produce market, and (a particular favourite of the founding student class) the Vorres Museum, a remarkable collection of Greek folk and contemporary art ten minutes from campus on foot.",
  "life.clubs.eyebrow": "Student Organisations",
  "life.clubs.h2": "Clubs, Societies and Student Initiatives",
  "life.clubs.intro": "EEA's founding class has already chartered 14 student organisations.",
  "life.clubs.c1.h3": "Daedalus Society (Solar Boat Team)",
  "life.clubs.c1.p": "Designs and races a solar electric boat in the Monaco Energy Boat Challenge. 28 active members. Won qualification status in April 2026.",
  "life.clubs.c1.tag": "Engineering · Competitions",
  "life.clubs.c2.h3": "EEA Robotics",
  "life.clubs.c2.p": "Builds mobile and humanoid robots in the Mechatronics Hall. Affiliated with the Hellenic Robotics Association.",
  "life.clubs.c2.tag": "Engineering · Competitions",
  "life.clubs.c3.h3": "Hellenic Bridge Builders",
  "life.clubs.c3.p": "Civil engineering student society. Runs the annual Build-a-Bridge competition and field trips to Greek infrastructure sites.",
  "life.clubs.c3.tag": "Engineering",
  "life.clubs.c4.h3": "Open Source @ EEA",
  "life.clubs.c4.p": "Weekly hack sessions. Maintains five small open-source tools used by the school's IT team.",
  "life.clubs.c4.tag": "Tech",
  "life.clubs.c5.h3": "EEA Debating Society",
  "life.clubs.c5.p": "Bilingual (Greek and English) parliamentary-style debating. Hosts a monthly public debate at the Onassis Library.",
  "life.clubs.c5.tag": "Culture",
  "life.clubs.c6.h3": "Filomousoi — Choir &amp; Ensemble",
  "life.clubs.c6.p": "30-voice choir and a 10-piece chamber ensemble. Performs at the Vorres Museum and the Megaron Athens.",
  "life.clubs.c6.tag": "Music",
  "life.clubs.c7.h3": "EEA Hiking &amp; Climbing",
  "life.clubs.c7.p": "Weekend trips to Hymettus, Parnitha, Penteli and Meteora. 60 members. Equipment loans available.",
  "life.clubs.c7.tag": "Sports",
  "life.clubs.c8.h3": "Football Club \"AOEEA\"",
  "life.clubs.c8.p": "Plays in the Attica Inter-University 5-a-side league. Home matches every other Saturday on the campus pitch.",
  "life.clubs.c8.tag": "Sports",
  "life.clubs.c9.h3": "EEA Sailing",
  "life.clubs.c9.p": "Trains weekly at the Nautical Club of Vouliagmeni. EEA students get a 30 % membership discount.",
  "life.clubs.c9.tag": "Sports",
  "life.clubs.c10.h3": "Filopolis — Heritage Society",
  "life.clubs.c10.p": "Architecture students leading documentation visits to neglected Mediterranean heritage sites in Attica.",
  "life.clubs.c10.tag": "Culture · Engineering",
  "life.clubs.c11.h3": "EEA Investment Club",
  "life.clubs.c11.p": "Manages a paper portfolio. Hosts visiting CFOs and runs a yearly venture-evaluation workshop with HEDNO.",
  "life.clubs.c11.tag": "Career",
  "life.clubs.c12.h3": "EEA Hellenic Folk Dance",
  "life.clubs.c12.p": "Traditional dances from across Greece. Open to all students; no prior experience needed.",
  "life.clubs.c12.tag": "Culture",
  "life.housing.h2": "Housing",
  "life.housing.p1": "EEA does not yet operate its own residence — construction of our 250-bed student residence is scheduled for autumn 2027. In the meantime, our Office of Student Affairs partners with three serviced student-housing operators in the surrounding municipalities (Peania, Paiania, Glyka Nera, and Spata). Admitted students receive housing application links eight weeks before the term begins, with average rents of €380 – €650 / month for a shared apartment.",
  "life.dining.h2": "Dining",
  "life.dining.p1": "Our Student Centre cafeteria operates Monday – Friday 08:00 – 19:00 and offers Mediterranean lunch menus at a subsidised flat price of €5.50 (€3.50 for need-based-bursary holders). Two coffee shops, a bakery, and three tavernas on the Peania main square — all within ten minutes of campus — round out the daily options.",
  "life.dining.p2": "An EEA student-led food cooperative (\"Δημητριακή\") operates a weekly direct-from-producer fruit and vegetable order. Many staff and students join.",
  "life.sports.h2": "Sports &amp; Wellbeing",
  "life.sports.p1": "The campus has an outdoor 5-a-side football pitch, a full basketball court, and an outdoor multi-purpose court. EEA has a partnership agreement with the Peania Municipal Swimming Pool (subsidised access for all students) and with the Nautical Club of Vouliagmeni (sailing). A 350 m² indoor gym is part of the phase-two construction scheduled for completion in 2027.",
  "life.sports.p2": "The EEA Counselling Service is open Monday – Friday with one full-time licensed psychologist and a part-time consultant. All consultations are confidential and free for enrolled students.",
  "life.culture.h2": "Culture in and around Peania",
  "life.culture.p1": "Living in Peania puts every major Athenian cultural venue within easy reach: the Athens Concert Hall, the Stavros Niarchos Foundation Cultural Center, the National Theatre, and the National Museum of Contemporary Art are all 30 – 50 minutes by metro or car. The Acropolis itself is forty minutes away. Closer to campus, the Vorres Museum (10 minutes on foot) is a remarkable collection of Greek folk and contemporary art set in a beautiful courtyard, and the Markopoulo wine region is fifteen minutes by car.",
  "life.spiritual.h2": "Spiritual Life",
  "life.spiritual.p1": "EEA respects every spiritual tradition. A quiet/prayer room is open daily in the Student Centre. The historic Church of the Holy Apostles of Peania (10 minutes' walk from campus) is the principal Orthodox parish. The Athens Catholic Cathedral, the Athens Synagogue, and the Athens Central Mosque are all within reach of central Athens.",
  "life.side.quick": "Quick Links",
  "life.side.housing": "Housing Portal",
  "life.side.card": "Student Card",
  "life.side.counsel": "Counselling Service",
  "life.side.health": "Health Service",
  "life.side.disability": "Disability Support",
  "life.side.conduct": "Code of Conduct",
  "life.side.getting": "Getting to Campus",
  "life.side.getting.p": "From Athens centre: Metro Line 3 to Doukissis Plakentias, then bus 319 or 308 (20 min).<br>From Airport: Bus 319 (10 min) or taxi (€12 – €15).<br>By car: Attiki Odos exit 18 (\"Peania South\").</p>\n                </aside>",
  "careers.bc": "Careers",
  "careers.h1": "Build Your Career at EEA",
  "careers.tagline": "Join a young, ambitious engineering institute at a defining moment.",
  "careers.why.h2": "Why Work at EEA",
  "careers.why.p1": "Elliniki Engineering Academy is a new institution, and that means real opportunity. Six months in, we are still actively building our founding faculty and core administrative team. Joining us means joining the people who will shape this institution for the long term.",
  "careers.why.p2": "We are committed to being an excellent place to work. Faculty members receive nine-month contracts with paid summer research months, a competitive Athens-region salary, full Greek social-security and supplementary private health cover, and an annual personal research budget. Administrative staff receive 14 salary-months a year (per Greek practice), 25 days of paid leave, and a hybrid working policy after the first six months in role.",
  "careers.openings.h2": "Current Openings",
  "careers.col1": "Role",
  "careers.col2": "Department",
  "careers.col3": "Closing",
  "careers.r1c1": "Assistant Professor — Power Electronics",
  "careers.r1c2": "Electrical Engineering",
  "careers.r1c3": "30 Jun 2026",
  "careers.r2c1": "Assistant Professor — Geotechnical Engineering",
  "careers.r2c2": "Civil Engineering",
  "careers.r2c3": "15 Jul 2026",
  "careers.r3c1": "Postdoctoral Researcher — Marine Energy",
  "careers.r3c2": "AMEL Lab",
  "careers.r3c3": "20 Jun 2026",
  "careers.r4c1": "Postdoctoral Researcher — AI Verification",
  "careers.r4c2": "ITAS Lab",
  "careers.r4c3": "30 Jun 2026",
  "careers.r5c1": "Library Assistant",
  "careers.r5c2": "Onassis Library",
  "careers.r5c3": "10 Jun 2026",
  "careers.r6c1": "Senior Admissions Officer",
  "careers.r6c2": "Admissions Office",
  "careers.r6c3": "15 Jun 2026",
  "careers.r7c1": "Estates Engineer (Building Services)",
  "careers.r7c2": "Estates &amp; Facilities",
  "careers.r7c3": "20 Jun 2026",
  "careers.r8c1": "Career Services Coordinator",
  "careers.r8c2": "Career Services",
  "careers.r8c3": "30 Jun 2026",
  "careers.r9c1": "Lab Technician (Mechatronics)",
  "careers.r9c2": "Mechanical Engineering",
  "careers.r9c3": "20 Jun 2026",
  "careers.howapply": "All applications should be sent to <strong>hr@eea.edu.gr</strong> with the role title in the subject line. Please include a CV, a one-page cover letter, and (for academic positions) three referees.",
  "careers.equal.h2": "Equal Opportunities",
  "careers.equal.p": "EEA is committed to fair recruitment without regard to gender, age, ethnicity, nationality, religion, disability, sexual orientation or family status. We particularly encourage applications from groups currently underrepresented in Greek engineering academia.",
  "careers.side.hr": "Contact HR",
  "careers.side.working": "Working at EEA",
  "careers.side.benefits": "Benefits overview",
  "careers.side.relo": "Relocation support",
  "careers.side.faculty": "Faculty appointments",
  "careers.side.equal": "Equal opportunities",
  "careers.side.hr.p": "Office of Human Resources<br>\n                        Building A, Floor 1<br>\n                        +30 210 36543069 (ext. 130)<br>\n                        hr@eea.edu.gr\n                    </p>\n                    Working at EEA\n                    <ul>\n                        <li>Benefits overview</li>\n                        <li>Relocation support</li>\n                        <li>Faculty appointments</li>\n                        <li>Equal opportunities</li>\n                    </ul>\n                </aside>\n            </div>",
  "contact.get.h3": "Get in Touch",
  "contact.addr.h4": "Address",
  "contact.addr.p": "Κρήτης 45, Peania 190 02<br>Attica, Greece</p>",
  "contact.phone.h4": "Phone",
  "contact.phone.p": "+30 210 36543069<br><span style=\"font-size:.85rem;opacity:.8\">Monday – Friday, 09:00 – 18:00 EET</span></p>",
  "contact.email.h4": "Email",
  "contact.email.p": "General: info@eea.edu.gr<br>Admissions: admissions@eea.edu.gr<br>Media: press@eea.edu.gr</p>\n                        </div>",
  "contact.hours.h4": "Office Hours",
  "contact.hours.p": "Monday – Friday: 09:00 – 18:00<br>Saturday: 10:00 – 14:00 (admissions only)<br>Sunday: closed</p>\n                        </div>",
  "contact.form.h3": "Send us a message",
  "contact.form.intro": "Fill in the form below and a member of the appropriate department will reply within two working days.",
  "contact.form.name": "Full Name *",
  "contact.form.email": "Email Address *",
  "contact.form.phone": "Phone (optional)",
  "contact.form.topic": "I am writing about *",
  "contact.form.select": "Please select…",
  "contact.form.opt1": "Undergraduate admissions",
  "contact.form.opt2": "Master's admissions",
  "contact.form.opt3": "Scholarships &amp; financial aid",
  "contact.form.opt4": "International students",
  "contact.form.opt5": "Industry partnerships",
  "contact.form.opt6": "Media / press enquiry",
  "contact.form.opt7": "Other",
  "contact.form.message": "Message *",
  "contact.form.consent": "I have read and agree to the EEA Privacy Policy",
  "contact.form.send": "Send Message",
  "contact.findus.h2": "Find Us",
  "contact.findus.p": "The EEA campus is located on Κρήτης 45, Peania, 25 minutes from central Athens.",
  "contact.map.larger": "View larger map",
  "contact.depts.h2": "Contact Specific Departments",
  "contact.d1.h3": "Admissions Office",
  "contact.d1.p": "For undergraduate and master's applications, scholarships, transcripts.",
  "contact.d1.info": "<strong>Phone:</strong> +30 210 36543069 (ext. 100)<br><strong>Email:</strong> admissions@eea.edu.gr</p>",
  "contact.d2.h3": "International Office",
  "contact.d2.p": "For non-EU students — visas, residence permits, accommodation.",
  "contact.d2.info": "<strong>Phone:</strong> +30 210 36543069 (ext. 105)<br><strong>Email:</strong> international@eea.edu.gr</p>",
  "contact.d3.h3": "Office of the Registrar",
  "contact.d3.p": "Enrolment certificates, degree attestations, official transcripts.",
  "contact.d3.info": "<strong>Phone:</strong> +30 210 36543069 (ext. 110)<br><strong>Email:</strong> registrar@eea.edu.gr</p>",
  "contact.d4.h3": "IT Support",
  "contact.d4.p": "Student / faculty portal, email account issues, eduroam.",
  "contact.d4.info": "<strong>Phone:</strong> +30 210 36543069 (ext. 200)<br><strong>Email:</strong> it-support@eea.edu.gr</p>",
  "contact.d5.h3": "Career Services",
  "contact.d5.p": "Internships, placement programme, employer enquiries.",
  "contact.d5.info": "<strong>Phone:</strong> +30 210 36543069 (ext. 150)<br><strong>Email:</strong> careers@eea.edu.gr</p>",
  "contact.d6.h3": "Research Office",
  "contact.d6.p": "Grant administration, contract research, visiting scholars.",
  "contact.d6.info": "<strong>Phone:</strong> +30 210 36543069 (ext. 180)<br><strong>Email:</strong> research@eea.edu.gr</p>",
  "ev.june.h2": "June 2026",
  "ev.mon.jun": "Jun",
  "ev.e1.h3": "Open House — Autumn 2026 Applicants",
  "ev.e1.p": "Tour the Peania campus, attend a sample lecture in Computer Engineering, meet faculty advisors. Family members welcome.",
  "ev.e1.time": "🕘 10:00 – 16:00",
  "ev.e1.loc": "📍 Main Hall, Building A",
  "ev.e1.fee": "🎟 Free, registration required",
  "ev.btn.register": "Register",
  "ev.e2.h3": "Public Lecture: \"Earthquake Engineering in the Age of Climate Adaptation\"",
  "ev.e2.p": "Prof. Andreas Papadopoulos (Dean, Civil &amp; Structural Engineering). Lecture in Greek with English simultaneous translation.",
  "ev.e2.time": "🕖 19:00",
  "ev.e2.loc": "📍 Auditorium \"Pythagoras\"",
  "ev.e2.fee": "🎟 Free, open to the public",
  "ev.btn.details": "Details",
  "ev.e3.h3": "EEA × Hellenic Solar Industry Symposium",
  "ev.e3.p": "One-day industry symposium hosted with the Hellenic Association of Photovoltaic Companies. Lunch included.",
  "ev.e3.time": "🕘 09:30 – 17:30",
  "ev.e3.loc": "📍 Conference Centre",
  "ev.e3.fee": "🎟 €40, free for students",
  "ev.e4.h3": "Daedalus Society Sponsorship Reception",
  "ev.e4.p": "Meet the EEA solar-boat team and view \"Daedalus I\" before it ships to Monaco. Open to all members of the EEA community and friends.",
  "ev.e4.time": "🕢 19:30 – 22:00",
  "ev.e4.loc": "📍 Mechatronics Hall (Building B)",
  "ev.btn.rsvp": "RSVP",
  "ev.e5.h3": "Early-Decision Application Deadline (Autumn 2026)",
  "ev.e5.p": "Final day to submit your application for the Founder's Scholarship pathway. Applications close at 23:59 EET.",
  "ev.e5.time": "🕛 23:59 EET",
  "ev.e5.loc": "📍 apply.eea.edu.gr",
  "ev.btn.apply": "Apply",
  "ev.july.h2": "July 2026",
  "ev.mon.jul": "Jul",
  "ev.e6.h3": "Daedalus I @ Monaco Solar &amp; Energy Boat Challenge",
  "ev.e6.p": "The EEA Daedalus Society competes in Monaco from 1 to 6 July. Follow the boat live via the team's social channels.",
  "ev.e6.loc": "📍 Monaco (Yacht Club de Monaco)",
  "ev.btn.background": "Background",
  "ev.e7.h3": "EEA × TEE Summer School — Earthquake Engineering",
  "ev.e7.p": "Five-day summer school co-organised with the Technical Chamber of Greece. Open to EEA students and chartered TEE engineers. €120 (free for EEA students).",
  "ev.e7.date": "📅 07 – 11 Jul",
  "ev.e7.loc": "📍 Auditorium \"Pythagoras\"",
  "ev.e8.h3": "End-of-Year Faculty Dinner",
  "ev.e8.p": "An invitation-only event for EEA faculty and staff to mark the end of the founding academic year.",
  "ev.e8.time": "🕢 19:30",
  "ev.e8.loc": "📍 Vorres Museum gardens",
  "ev.e9.h3": "Regular Admissions Deadline (Autumn 2026)",
  "ev.e9.p": "Closing date for the main 2026 admissions round.",
  "ev.e9.time": "🕛 23:59 EET",
  "ev.e9.loc": "📍 apply.eea.edu.gr",
  "ev.aug.h2": "August 2026",
  "ev.mon.aug": "Aug",
  "ev.e10.h3": "Public Holiday — Dormition of the Theotokos",
  "ev.e10.p": "Campus closed. Administrative services resume on 18 August.",
  "ev.e11.h3": "Open House — Last Chance Late Round",
  "ev.e11.p": "Final open day before the late admissions round. Includes a panel with current first-year students.",
  "ev.e11.time": "🕓 16:00 – 20:00",
  "ev.e11.loc": "📍 Main Hall, Building A",
  "ev.sep.h2": "September 2026",
  "ev.mon.sep": "Sep",
  "ev.e12.h3": "Late Admissions Deadline",
  "ev.e12.p": "Final closing date for any remaining seats in the 2026 intake.",
  "ev.e13.h3": "New Student Orientation Week 2026/27",
  "ev.e13.p": "Welcome programme for incoming undergraduates and their families. Includes a campus tour, departmental briefings and a traditional Greek dinner at the Vorres Museum.",
  "ev.e13.date": "📅 21 – 25 Sep",
  "ev.e13.loc": "📍 Throughout campus",
  "ev.e14.h3": "First Day of Lectures — 2026/27 Winter Semester",
  "fp.maintenance": "Scheduled maintenance window: Sunday 31 May 2026, 02:00–04:00 EET. The portal will be briefly unavailable.",
  "fp.or": "— OR —",
  "fp.sso": "Sign in with Single Sign-On (SSO)",
  "lib.bc": "Onassis Library",
  "lib.h1": "The Onassis Library",
  "lib.tagline": "22,000 volumes, 18 major databases, and quiet study from dawn to dusk.",
  "lib.about.h2": "About the Library",
  "lib.about.p": "The Onassis Library is EEA's principal academic resource centre, occupying the upper two floors of Building A on the Peania campus. The library was endowed at the institute's founding by a grant from the Alexander S. Onassis Public Benefit Foundation and was officially inaugurated alongside the Academy itself in November 2025.",
  "lib.coll.h2": "Collection",
  "lib.coll.p": "The library currently holds 22,000 physical volumes acquired through a curated founding-collection programme led by the library's first head, Dr. Ariadne Romaiou. Acquisitions focus on the core engineering literature, complemented by smaller working collections in the history of science, classical philosophy, and the Greek and Mediterranean architectural canon. We add roughly 80 new physical titles per month.",
  "lib.electronic.h3": "Electronic Resources",
  "lib.electronic.p": "EEA students and staff have full access to 18 major academic databases:",
  "lib.db.1": "IEEE Xplore (full)",
  "lib.db.2": "ACM Digital Library",
  "lib.db.3": "ScienceDirect &amp; Scopus",
  "lib.db.4": "Springer Nature",
  "lib.db.5": "Wiley Online Library",
  "lib.db.6": "Taylor &amp; Francis Online",
  "lib.db.7": "JSTOR",
  "lib.db.8": "Cambridge Core",
  "lib.db.9": "Oxford Academic",
  "lib.db.10": "ASCE Library (Civil Engineering)",
  "lib.db.11": "ASME Digital Collection (Mechanical)",
  "lib.db.12": "ICE Virtual Library (Civil &amp; Geotechnical)",
  "lib.db.13": "Architectural Publications Index",
  "lib.db.14": "WGSN (Architecture &amp; Design trends)",
  "lib.db.15": "Statista &amp; OECD iLibrary",
  "lib.db.16": "Greek Heal-Link consortium",
  "lib.db.17": "Web of Science",
  "lib.db.18": "Google Scholar institutional subscription",
  "lib.hours.h2": "Opening Hours",
  "lib.hours.col1": "Day",
  "lib.hours.col2": "Hours",
  "lib.hours.r1c1": "Monday – Thursday",
  "lib.hours.r1c2": "08:00 – 22:00",
  "lib.hours.r2c1": "Friday",
  "lib.hours.r2c2": "08:00 – 20:00",
  "lib.hours.r3c1": "Saturday",
  "lib.hours.r3c2": "10:00 – 18:00",
  "lib.hours.r4c1": "Sunday",
  "lib.hours.r4c2": "Closed (24-hour study room remains open with student card)",
  "lib.hours.note": "During the examinations period (early Feb &amp; mid-Jun – early Jul) the library extends to a 07:00 – 24:00 schedule.",
  "lib.services.h2": "Services",
  "lib.services.s1": "Borrow: 6 books / 30 days for undergraduates · 12 books / 90 days for postgraduates and staff",
  "lib.services.s2": "Inter-library loans via the Greek Heal-Link consortium",
  "lib.services.s3": "Reference and research-help service (in person, email or chat) Mon-Fri 10:00 – 17:00",
  "lib.services.s4": "Booking of 14 group-study rooms (4 to 12 person) via the student portal",
  "lib.services.s5": "Printing &amp; scanning, including A1/A0 plotting for architecture students",
  "lib.services.s6": "Course-reserve programme — every required textbook is on closed-reserve loan",
  "lib.services.s7": "Workshops in research-tools, reference managers (Zotero) and academic writing",
  "lib.side.quick": "Quick Links",
  "lib.side.opac": "Catalogue (OPAC)",
  "lib.side.offcampus": "Off-campus access",
  "lib.side.book": "Book a study room",
  "lib.side.purchase": "Request a purchase",
  "lib.side.guides": "Subject guides",
  "lib.side.contact": "Contact",
  "lib.side.contact.p": "Onassis Library, Building A (floors 2-3)<br>\n                        +30 210 36543069 (ext. 220)<br>\n                        library@eea.edu.gr\n                    </p>\n                </aside>",
  "login.student.desc": "Course enrolment, transcripts, library, timetable, internships",
  "login.continue": "Continue →",
  "login.faculty.desc": "Class management, grading, research administration, HR",
  "news.daedalus.bc": "21 Apr 2026",
  "news.daedalus.h1": "\"Daedalus I\" Qualifies for Monaco Solar &amp; Energy Boat Challenge",
  "news.daedalus.meta": "Daedalus Society · 21 April 2026 · 3 min read",
  "news.daedalus.lede": "The EEA Daedalus Society — the Academy's student solar-boat team — has been officially admitted to the 2026 Monaco Solar &amp; Energy Boat Challenge, becoming the first Greek student entry in the competition in five years.",
  "news.daedalus.p1": "The boat, \"Daedalus I,\" was designed and built between January and April 2026 in the Mechatronics Hall, primarily by 14 first-year students from the Mechanical Engineering and Electrical &amp; Energy Systems programmes. The qualification submission package — a 60-page technical dossier and a five-minute construction-progress video — was accepted by the Yacht Club de Monaco's selection committee on 18 April.",
  "news.daedalus.boat.h2": "About the boat",
  "news.daedalus.boat.b1": "<strong>Hull:</strong> 4.5 m carbon-fibre catamaran, vacuum-bagged in the Mechatronics Hall composites bay",
  "news.daedalus.boat.b2": "<strong>Propulsion:</strong> 4 kW brushless DC outboard, custom controller built around an STM32 MCU",
  "news.daedalus.boat.b3": "<strong>Solar array:</strong> 1.6 kWp monocrystalline panels donated by a sponsor",
  "news.daedalus.boat.b4": "<strong>Battery:</strong> 5 kWh LiFePO₄ pack, custom BMS designed by the Electrical sub-team",
  "news.daedalus.boat.b5": "<strong>Weight (empty, ready to launch):</strong> 165 kg",
  "news.daedalus.boat.b6": "<strong>Top speed (test runs at Vouliagmeni):</strong> 14 knots",
  "news.daedalus.quote": "\"This is what an engineering school is for,\" said Prof. Mavrogiannis, Dean of Mechanical Engineering and faculty advisor to the team. \"Fourteen first-year students built a functioning, regulation-compliant solar racing catamaran in nine weeks. Nobody told them what was supposed to be hard about it. They just did it.\"",
  "news.daedalus.next.h2": "What's next",
  "news.daedalus.next.p": "The Monaco Solar &amp; Energy Boat Challenge will be held from 1 to 6 July 2026. The Daedalus Society will compete in the Solar Class. The team is currently fundraising for travel and shipping costs (estimated €18,000) — a public call to the EEA community will be issued in mid-May, and a corporate sponsorship round is being co-ordinated with the EEA Career Services Office.",
  "news.daedalus.side.team": "The Team",
  "news.daedalus.side.t1": "<strong>Members:</strong> 28",
  "news.daedalus.side.t2": "<strong>Builders:</strong> 14 Y1 students",
  "news.daedalus.side.t3": "<strong>Advisor:</strong> Prof. N. Mavrogiannis",
  "news.daedalus.side.t4": "<strong>Build time:</strong> 9 weeks",
  "news.daedalus.side.support": "Support the Team",
  "news.daedalus.side.sponsor": "Sponsor Daedalus",
  "news.karagianni.bc": "28 Apr 2026",
  "news.karagianni.h1": "Prof. Eleni Karagianni Joins EEA from EPFL",
  "news.karagianni.meta": "Office of the Rector · 28 April 2026 · 3 min read",
  "news.karagianni.lede": "EEA is delighted to announce the appointment of Prof. Eleni Karagianni as the Academy's first holder of the Hephaestus Chair in Computational Materials Science. Prof. Karagianni joins EEA from the École Polytechnique Fédérale de Lausanne (EPFL), where she has held a tenured Associate Professorship since 2019.",
  "news.karagianni.p1": "The Hephaestus Chair is one of four endowed faculty positions established at EEA's founding, funded by the Athens Engineering Trust. It carries with it a five-year research budget and a small dedicated computational research group.",
  "news.karagianni.focus.h2": "Research focus",
  "news.karagianni.focus.p1": "Prof. Karagianni's work sits at the intersection of computational mechanics and materials science. She is best known for her contributions to multi-scale modelling of cyclic fatigue in masonry — a research area with direct application to the conservation of historic Mediterranean structures. At EEA she will lead the institute's contribution to the Horizon Europe project STONEAGE, building a database of historic Mediterranean masonry behaviour under cyclic loading, in collaboration with the Laboratory for Mediterranean Built Heritage (LIMBH) under Dr. Petrakis.",
  "news.karagianni.focus.p2": "She will also teach the second-year undergraduate course \"Mechanics of Materials\" in the Civil &amp; Structural Engineering programme, beginning in winter semester 2026/27.",
  "news.karagianni.return.h2": "A diaspora return",
  "news.karagianni.return.p1": "Prof. Karagianni's appointment makes her the eleventh diaspora return academic to join EEA — a deliberate part of the Academy's faculty strategy. \"We are not pretending that we can compete head-to-head with the world's best universities on every dimension,\" said founding rector Prof. Vlachos. \"But we can offer talented Greek academics a serious institution, a real research budget, and the chance to build something. That is a proposition that an increasing number of senior people are finding more attractive than yet another year abroad.\"",
  "news.karagianni.return.p2": "Asked why she chose to come back, Prof. Karagianni said: \"I had two reasons. The first is that I want my children to grow up in Greece. The second is more professional: STONEAGE is, intellectually, the most exciting project of my career so far, and EEA is the right place to host it. I am very glad to be here.\"",
  "news.karagianni.side.bio": "Quick Bio",
  "news.karagianni.side.b1": "<strong>Position:</strong> Hephaestus Chair, Computational Materials",
  "news.karagianni.side.b2": "<strong>From:</strong> EPFL (2019–2026)",
  "news.karagianni.side.b3": "<strong>PhD:</strong> Imperial College London (2014)",
  "news.karagianni.side.b4": "<strong>Teaching:</strong> Mechanics of Materials (Y2)",
  "news.karagianni.side.related": "Related",
  "news.karagianni.side.r1": "EEA Research Centres",
  "news.karagianni.side.r2": "Faculty Leadership",
  "news.scholarships.bc": "03 May 2026",
  "news.scholarships.h1": "50 Founder's Scholarships Announced for the Autumn 2026 Intake",
  "news.scholarships.meta": "Admissions Office · 03 May 2026 · 4 min read",
  "news.scholarships.lede": "The Elliniki Engineering Academy Board of Trustees has approved a 50-award Founder's Scholarship programme for the school's second incoming class, the Autumn 2026 intake. Awards will range from a 30 % to a 70 % reduction of full tuition, applied across the full duration of the awarded student's undergraduate degree.",
  "news.scholarships.p1": "Funding for the programme comes from the founding endowment created at EEA's incorporation in 2024 — a deliberate decision by the founders to dedicate a meaningful share of the initial capital to making the school accessible from year one. \"The point of building this institution was never to make it for people who already had the means to attend it,\" said Dr. Maria Stamatopoulou, Vice-Rector for Academic Affairs and chair of the scholarships committee. \"Fifty awards in our second year is, in proportion to our cohort size, one of the most generous merit-based programmes in Greek higher education.\"",
  "news.scholarships.elig.h2": "Eligibility",
  "news.scholarships.elig.b1": "Applicants holding Greek, Cypriot or other EU citizenship.",
  "news.scholarships.elig.b2": "Applying to any of the six undergraduate EEA programmes for the autumn 2026 intake.",
  "news.scholarships.elig.b3": "Demonstrated academic strength in mathematics and science (Apolytirio Lykeiou 18+/20, IB 36+ /42, A-Levels A*A*A or equivalent — full equivalence table on the admissions page).",
  "news.scholarships.elig.b4": "A short scholarship statement of motivation (500 words, Greek or English).",
  "news.scholarships.how.h2": "How it works",
  "news.scholarships.how.p1": "Applicants opt into the Founder's Scholarship pathway when submitting their main EEA application. A scholarships sub-committee reviews all eligible applications and ranks them on academic record alone (the motivation statement is used only as a tie-breaker). The top 50 candidates receive offers; the next 20 are placed on a waitlist.",
  "news.scholarships.how.p2": "Once awarded, scholarship coverage applies for the full duration of the degree, provided the student maintains a minimum grade-point average of 7.0/10 at the end of each year.",
  "news.scholarships.dates.h2": "Key dates",
  "news.scholarships.dates.b1": "<strong>30 June 2026 — application deadline</strong> (both EEA application and Founder's Scholarship pathway)",
  "news.scholarships.dates.b2": "21 July 2026 — scholarship decisions released",
  "news.scholarships.dates.b3": "05 August 2026 — accepted students must confirm their place",
  "news.scholarships.other": "Three further EEA scholarship schemes will continue to operate in parallel: the Diaspora Scholarship (15 awards / year, 25 % tuition reduction for students of Greek heritage holding a non-Greek passport); the Hephaestus Industry Sponsorships (six full-tuition sponsorships with a paid summer internship); and the Pythia Women-in-Engineering Award (10 awards / year, 40 % of tuition).",
  "news.scholarships.side.apply.h4": "Apply for the Scholarship",
  "news.scholarships.side.apply.p": "Submit your main EEA application <strong>and</strong> opt into the Founder's Scholarship pathway by 30 June 2026.",
  "news.scholarships.side.begin": "Begin Application",
  "news.scholarships.side.other.h4": "Other Awards",
  "news.scholarships.side.diaspora": "Diaspora Scholarship",
  "news.scholarships.side.hephaestus": "Hephaestus Sponsorship",
  "news.scholarships.side.pythia": "Pythia Award",
  "news.mechatronics.bc": "15 May 2026",
  "news.mechatronics.h1": "Mechatronics Hall Officially Opens",
  "news.mechatronics.meta": "Communications Office · 15 May 2026 · 3 min read",
  "news.mechatronics.lede": "The Mechatronics Hall — EEA's 800 m² flagship engineering laboratory — was inaugurated on Thursday in a small ceremony attended by founding faculty, current undergraduates, and representatives from KUKA Robotics Hellas, the German robotics manufacturer that supplied six collaborative robots to the facility.",
  "news.mechatronics.p1": "Located in Building B of the Peania campus, the Hall has been operational on a soft-launch basis since February 2026 but has now received final occupancy and safety certification from the East Attica regional authority. With this, the space is open to all undergraduate students in the Mechanical Engineering and Computer Engineering programmes, with structured workshop slots through the Department of Mechanical Engineering.",
  "news.mechatronics.inside.h2": "What's inside",
  "news.mechatronics.inside.b1": "Six KUKA LBR iiwa collaborative robotic arms, with three additional cells for industrial robot programming exercises.",
  "news.mechatronics.inside.b2": "Additive manufacturing area with twelve fused-deposition printers, three resin printers, and one industrial-grade Markforged X7 carbon-fibre printer.",
  "news.mechatronics.inside.b3": "A small-scale (1 × 1 m test section) low-speed wind tunnel for undergraduate aerodynamics labs.",
  "news.mechatronics.inside.b4": "Two single-cylinder propulsion test cells, with mechanical and instrumentation upgrade scheduled for late 2026.",
  "news.mechatronics.inside.b5": "A CNC machining bay (two 3-axis mills and one CNC lathe) for prototype fabrication.",
  "news.mechatronics.inside.b6": "Open-plan project area equipped to host the Daedalus Society Solar Boat build.",
  "news.mechatronics.quote": "\"What this facility lets us do is teach engineering the way engineering is actually practised,\" said Prof. Nikos Mavrogiannis, Dean of Mechanical Engineering. \"Our second-year mechatronics module already runs entirely as a project-based course in this hall. Our students leave it knowing how to design, build and debug a real system, not just analyse it on paper.\"",
  "news.mechatronics.open.h2": "Open to students from all departments",
  "news.mechatronics.open.p": "Although the Mechatronics Hall is administered by the Department of Mechanical Engineering, structured workshop access is available to any EEA undergraduate after completing the half-day mandatory safety induction. The next induction sessions are scheduled for 26 May, 9 June and 23 June. Bookings are made through the student portal.",
  "news.mechatronics.side.info": "Quick Info",
  "news.mechatronics.side.i1": "<strong>Location:</strong> Building B",
  "news.mechatronics.side.i2": "<strong>Area:</strong> 800 m²",
  "news.mechatronics.side.i3": "<strong>Hours:</strong> Mon-Fri 09:00 – 21:00",
  "news.mechatronics.side.i4": "<strong>Access:</strong> Safety induction required",
  "news.mechatronics.side.more": "More News",
  "news.mechatronics.side.tee": "TEE MoU signed",
  "news.mechatronics.side.daedalus": "Daedalus qualifies",
  "news.tee.bc": "22 May 2026",
  "news.tee.h1": "EEA Signs Strategic MoU with the Hellenic Society of Engineers",
  "news.tee.meta": "Communications Office · 22 May 2026 · 4 min read",
  "news.tee.lede": "A formal Memorandum of Understanding was signed last week between Elliniki Engineering Academy and the Technical Chamber of Greece (Τεχνικό Επιμελητήριο Ελλάδος — TEE), the country's largest professional body of engineers, opening EEA students' access to one of Greece's most established engineering networks.",
  "news.tee.p1": "The agreement, signed at the TEE headquarters on Nikis Street in Athens on Thursday morning, was concluded between Prof. Dimitris Vlachos, founding rector of EEA, and TEE President George Stasinos. Under its terms, every EEA student will gain access to TEE mentorship pairings from their second year of study and free participation in TEE's continuing-professional-development workshops throughout their degree.",
  "news.tee.p2": "\"Six months into our existence, EEA is putting in place the institutional foundations that we will rely on for decades,\" said Prof. Vlachos at the signing. \"There is no more important relationship for a Greek engineering school than the one with the country's chartered engineers. This MoU formalises what has been a deep and very productive working relationship from day one.\"",
  "news.tee.p3": "President Stasinos described the partnership as \"a natural step. The Greek engineering profession needs more, not fewer, ambitious training institutions, and we welcome EEA into the wider professional community. Our 130,000 members are now also EEA's mentors.\"",
  "news.tee.means.h2": "What this means for EEA students",
  "news.tee.means.b1": "One-to-one mentorship pairings with chartered TEE members starting in the second year of undergraduate study.",
  "news.tee.means.b2": "Free access to all TEE continuing professional development workshops.",
  "news.tee.means.b3": "A guaranteed reserved place per EEA student at the annual TEE Career Forum.",
  "news.tee.means.b4": "Joint EEA – TEE summer schools, with the first scheduled for July 2026 on \"Earthquake Engineering: from theory to construction site practice\".",
  "news.tee.means.b5": "A streamlined pathway to TEE chartership for EEA graduates upon completion of the required professional practice period.",
  "news.tee.about.h2": "About TEE",
  "news.tee.about.p": "The Technical Chamber of Greece is the official advisor of the Greek state on matters of technical, scientific and developmental policy, and is the statutory body for the registration and recognition of professional engineers in Greece. Founded in 1923, it has around 130,000 members across all engineering disciplines.",
  "news.tee.side.share": "Share",
  "news.tee.side.sharelinks": "<a href=\"#\">Email</a> · <a href=\"#\">LinkedIn</a> · <a href=\"#\">X</a>",
  "news.tee.side.related": "Related",
  "news.tee.side.r1": "Mechatronics Hall opens",
  "news.tee.side.r2": "Founder's Scholarships",
  "news.tee.side.r3": "EEA Research",
  "news.list.tag.partnership": "Partnership",
  "news.list.n1.date": "22 May 2026",
  "news.list.n1.author": "Communications",
  "news.list.n1.h3": "EEA Signs Strategic MoU with the Hellenic Society of Engineers",
  "news.list.n1.p": "The Academy has formalised a partnership with the country's largest professional body, giving every EEA student access to the TEE Chamber's mentorship network from their second year onward.",
  "news.list.readmore": "Read more",
  "news.list.tag.facilities": "Facilities",
  "news.list.n2.date": "15 May 2026",
  "news.list.n2.author": "Communications",
  "news.list.n2.h3": "Mechatronics Hall Officially Opens",
  "news.list.n2.p": "The Academy's flagship 800 m² lab, featuring six KUKA collaborative robots and a small-scale wind tunnel, is now operational and open to all undergraduate mechanical and computer engineering students.",
  "news.list.tag.admissions": "Admissions",
  "news.list.n3.date": "03 May 2026",
  "news.list.n3.author": "Admissions Office",
  "news.list.n3.h3": "50 Founder's Scholarships Announced for Autumn 2026",
  "news.list.n3.p": "Awards range from 30 % to 70 % of full tuition. Open to applicants from Greece, Cyprus and the rest of the EU. Application deadline: 30 June 2026.",
  "news.list.tag.faculty": "Faculty",
  "news.list.n4.date": "28 April 2026",
  "news.list.n4.author": "Office of the Rector",
  "news.list.n4.h3": "Prof. Eleni Karagianni Joins EEA from EPFL",
  "news.list.n4.p": "The Academy welcomes its first chaired professor in Computational Materials Science. Prof. Karagianni will lead EEA's contribution to the Horizon Europe project STONEAGE on historic masonry behaviour.",
  "news.list.tag.studentlife": "Student Life",
  "news.list.n5.date": "21 April 2026",
  "news.list.n5.author": "Daedalus Society",
  "news.list.n5.h3": "Student Solar Boat Team Qualifies for Monaco 2026",
  "news.list.n5.p": "\"Daedalus I\" — built in just nine weeks in the Mechatronics Hall — becomes the first Greek student entry in the Monaco Solar &amp; Energy Boat Challenge in five years.",
  "news.list.tag.research": "Research",
  "news.list.n6.date": "14 April 2026",
  "news.list.n6.author": "Research Office",
  "news.list.n6.h3": "Horizon Europe Grant Awarded for Aegean Wave-Energy Research",
  "news.list.n6.p": "The Aegean Marine Energy Lab (AMEL) has secured a €1.4 M, three-year Horizon Europe grant to develop a wave-energy converter for low-energy Mediterranean wave climates.",
  "news.list.tag.community": "Community",
  "news.list.n7.date": "06 April 2026",
  "news.list.n7.author": "Communications",
  "news.list.n7.h3": "EEA Hosts Open Day for Local Secondary Schools",
  "news.list.n7.p": "More than 220 high-school students from East Attica attended EEA's first public open day. The next public open day will be held on 04 June 2026.",
  "news.list.tag.industry": "Industry",
  "news.list.n8.date": "31 March 2026",
  "news.list.n8.author": "Career Services",
  "news.list.n8.h3": "Internships Confirmed at 24 Partner Companies",
  "news.list.n8.p": "Every EEA undergraduate is now guaranteed at least one paid summer internship. Partners include METKA, Mytilineos, HEDNO, Athens International Airport and seven Athens-based deep-tech start-ups.",
  "news.list.tag.awards": "Awards",
  "news.list.n9.date": "20 March 2026",
  "news.list.n9.author": "Office of the Rector",
  "news.list.n9.h3": "EEA Founding Class Recognised by the President of the Hellenic Republic",
  "news.list.n9.p": "President Katerina Sakellaropoulou received an EEA delegation at the Presidential Mansion to mark the launch of Greece's newest engineering institute.",
  "news.list.tag.operations": "Operations",
  "news.list.n10.date": "12 March 2026",
  "news.list.n10.author": "Library Services",
  "news.list.n10.h3": "Onassis Library Adds 18 Academic Databases",
  "news.list.n10.p": "The Onassis Library has expanded its electronic resource subscription to cover the major IEEE, ACM, ScienceDirect, Springer and Taylor &amp; Francis collections.",
  "privacy.h1": "Privacy Policy",
  "privacy.tagline": "How we collect, use and protect personal data — GDPR-aligned.",
  "privacy.lastupdate": "Last updated: 1 April 2026 · Data Protection Officer: dpo@eea.edu.gr",
  "privacy.s1.h2": "1. Who We Are",
  "privacy.s1.p": "Elliniki Engineering Academy (EEA) is the data controller for the personal data we process. Our registered office is at Κρήτης 45, Peania 190 02, Greece. Contact: dpo@eea.edu.gr · +30 210 36543069.",
  "privacy.s2.h2": "2. What Data We Collect",
  "privacy.s2.p": "We collect the personal data you provide to us directly (in applications, in forms, in correspondence), and a limited set of operational data when you visit our website (server logs, cookies necessary to deliver the site, and an aggregated analytics cookie that we anonymise within 30 days).",
  "privacy.s3.h2": "3. Why We Process It",
  "privacy.s3.b1": "To process applications and administer admissions",
  "privacy.s3.b2": "To deliver our academic programmes to enrolled students",
  "privacy.s3.b3": "To fulfil our obligations as an employer of staff",
  "privacy.s3.b4": "To communicate with prospective students who have requested information",
  "privacy.s3.b5": "To meet our legal obligations to the Greek state and the European Union",
  "privacy.s4.h2": "4. Lawful Bases",
  "privacy.s4.p": "We rely on (a) contract — to provide our services to applicants, students and staff; (b) legal obligation — to comply with Greek and EU regulation; (c) legitimate interest — to operate the institution efficiently; and (d) consent — for optional marketing communications and non-essential cookies.",
  "privacy.s5.h2": "5. How Long We Keep It",
  "privacy.s5.p": "Application files of unsuccessful applicants are deleted within 18 months. Student records are kept for the standard statutory periods that apply to higher education in Greece. Employment records are kept for 10 years post-departure. Marketing-consent records are kept until withdrawn.",
  "privacy.s6.h2": "6. Your Rights",
  "privacy.s6.p": "Under the GDPR you have the right to access, rectify, port, restrict, object to the processing of, and (in the relevant circumstances) erase your personal data. Email <strong>dpo@eea.edu.gr</strong> to exercise any of these rights. You also have the right to lodge a complaint with the Hellenic Data Protection Authority (HDPA / ΑΠΔΠΧ).",
  "privacy.s7.h2": "7. Cookies",
  "privacy.s7.p": "This website uses one strictly-necessary cookie (session preference and language) and one anonymised analytics cookie. We do not run advertising trackers. You can disable analytics cookies in your browser settings without losing site functionality.",
  "privacy.s8.h2": "8. International Transfers",
  "privacy.s8.p": "Personal data is stored on servers located within the European Economic Area. Where a service provider is located outside the EEA, transfers occur only under appropriate safeguards (Standard Contractual Clauses or adequacy decisions).",
  "privacy.s9.h2": "9. Changes",
  "privacy.s9.p": "We may update this notice from time to time. Material changes will be notified to enrolled students and staff via the portals, and to wider visitors via this page.",
  "res.philosophy.h2": "An Applied Research Philosophy",
  "res.philosophy.p1": "EEA's research strategy follows a deliberately narrow focus. We have chosen four thematic priorities that match the engineering challenges Greece will face over the next decade — and on which we believe a small, agile institute can do work that matters. Faculty are recruited primarily on the strength of their fit with one of these priorities.",
  "res.philosophy.p2": "All EEA research is carried out under our <em>open-publication-by-default</em> policy: results are published in peer-reviewed venues and, wherever possible, made openly available through the European Open Science Cloud and our institutional repository.",
  "res.centres.h2": "Research Centres",
  "res.ceri.h3": "Centre for Earthquake-Resilient Infrastructure (CERI)",
  "res.ceri.p": "A joint research unit with the Earthquake Planning &amp; Protection Organisation (OASP). Focuses on structural retrofit techniques for the existing Greek building stock, seismic isolation systems, and rapid post-earthquake damage assessment.",
  "res.ceri.dir": "Director: Prof. A. Papadopoulos",
  "res.amel.h3": "Aegean Marine Energy Lab (AMEL)",
  "res.amel.p": "Research on wave and tidal energy converters adapted to the relatively low-energy Aegean wave climate, hybrid offshore PV-aquaculture platforms, and the integration of marine energy into Greek island grids.",
  "res.amel.dir": "Director: Prof. Y. Christoforou",
  "res.itas.h3": "Institute for Trustworthy AI Systems (ITAS)",
  "res.itas.p": "An engineering-led approach to AI safety and verification. Current projects include formal verification of neural network controllers for autonomous shipping and a multilingual benchmark suite for low-resource European languages.",
  "res.itas.dir": "Director: Dr. S. Lekka",
  "res.limbh.h3": "Laboratory for Mediterranean Built Heritage (LIMBH)",
  "res.limbh.p": "Combines structural conservation engineering, traditional materials science, and 3D documentation. Field partnerships include the Ephorate of Antiquities of East Attica and the Acropolis Restoration Service.",
  "res.limbh.dir": "Director: Dr. A. Petrakis",
  "res.projects.h2": "Current Major Projects",
  "res.projects.col1": "Project",
  "res.projects.col2": "Funder",
  "res.projects.col3": "Period",
  "res.projects.col4": "EEA Lead",
  "res.projects.r1c1": "SEISMORAPID — UAV-based rapid damage assessment for post-earthquake building triage",
  "res.projects.r1c2": "HFRI",
  "res.projects.r1c3": "2026 – 2028",
  "res.projects.r1c4": "CERI",
  "res.projects.r2c1": "AEGEANWAVE — Low-energy wave climate converter prototype for the Cyclades",
  "res.projects.r2c2": "Horizon Europe",
  "res.projects.r2c3": "2026 – 2029",
  "res.projects.r2c4": "AMEL",
  "res.projects.r3c1": "SAFEPILOT — Formal verification of autonomous coastal vessel controllers",
  "res.projects.r3c2": "EU Maritime Safety Agency",
  "res.projects.r3c3": "2026 – 2027",
  "res.projects.r3c4": "ITAS",
  "res.projects.r4c1": "STONEAGE — Database of historic Mediterranean masonry behaviour under cyclic loading",
  "res.projects.r4c2": "Horizon Europe (MSCA)",
  "res.projects.r4c3": "2026 – 2028",
  "res.projects.r4c4": "LIMBH",
  "res.projects.r5c1": "GREENGRID-PEANIA — Local DC micro-grid prototype on the EEA campus",
  "res.projects.r5c2": "HFRI + HEDNO",
  "res.projects.r5c3": "2026 – 2027",
  "res.projects.r5c4": "Dept. of Electrical Eng.",
  "res.industry.h2": "Industry Partnerships",
  "res.industry.p1": "EEA maintains an active network of 24 industry partners. Partnership comes in three forms: a curriculum advisory seat, internship placements (every EEA undergraduate is guaranteed at least one paid summer placement), and joint applied-research projects.",
  "res.industry.p2": "<strong>Current partners include:</strong> METKA, Mytilineos, HEDNO, OTE Group, Helleniq Energy, Hellenic Aerospace Industry, Beat (Taxibeat), Workable, BlueGround, Pamantis, Ergose, Klepsydra Technologies, Athens International Airport, Stergiopoulos &amp; Associates, Asprofos Engineering, Aegean Marine Petroleum, Mantis Business Innovation, ELPE, ENEL Green Power Hellas, TERNA Energy, GEK TERNA, Pegasus Shipping, NJV Athens Plaza Hotels (sustainability lab), and the National Observatory of Athens (geophysics).",
  "res.pub.h2": "Publishing &amp; Open Science",
  "res.pub.p1": "Faculty are evaluated on research outputs that are externally verifiable. We track three primary indicators: peer-reviewed publications, externally funded grant income, and patents / industrial transfer activity. All publications are deposited in the EEA institutional repository within thirty days of acceptance.",
  "res.pub.p2": "EEA's first peer-reviewed publications are scheduled for late 2026; in our six-month track record we have already secured three Horizon Europe grants and one HFRI grant, representing a combined €4.2 M of research income.",
  "res.side.centres": "Research Centres",
  "res.side.ceri": "CERI — Earthquake",
  "res.side.amel": "AMEL — Marine Energy",
  "res.side.itas": "ITAS — AI Systems",
  "res.side.limbh": "LIMBH — Built Heritage",
  "res.side.researchers": "For Researchers",
  "res.side.openings": "Open Positions",
  "res.side.visiting": "Visiting Scholars",
  "res.side.repo": "Institutional Repository",
  "res.side.ethics": "Ethics &amp; Integrity",
  "res.side.industry": "For Industry",
  "res.side.partner": "Become a Partner",
  "res.side.contract": "Contract Research",
  "res.side.ce": "Continuing Education",
  "sitemap.h1": "Sitemap",
  "sitemap.tagline": "All public pages on the EEA website.",
  "sitemap.main": "Main",
  "sitemap.aboutacademy": "About the Academy",
  "sitemap.res.overview": "Overview",
  "sitemap.community": "Community",
  "sitemap.careers": "Careers at EEA",
  "sitemap.legal": "Legal",
  "sp.format": "Format: eeaXXXXX (Student ID) or first.last (alias)",
  "sp.or": "— OR —",
  "terms.h1": "Terms of Use",
  "terms.tagline": "Conditions that govern your use of the EEA website.",
  "terms.lastupdate": "Last updated: 1 April 2026",
  "terms.s1.h2": "1. Acceptance",
  "terms.s1.p": "By using eea.edu.gr you accept these Terms of Use. If you do not accept them, please do not use the site.",
  "terms.s2.h2": "2. Content",
  "terms.s2.p": "The content of this website is published for general information about EEA and its activities. While we make reasonable efforts to keep information accurate and up to date, content is provided \"as is\" and may be amended without notice. Information about academic programmes, tuition and admissions is binding only when communicated in writing through the formal Admissions process.",
  "terms.s3.h2": "3. Intellectual Property",
  "terms.s3.p": "All material on this site (text, images, logos) is the property of Elliniki Engineering Academy or its licensors, and is protected by copyright. You may view, download and print content for personal, non-commercial use. Any other use requires our prior written permission.",
  "terms.s4.h2": "4. Third-Party Content",
  "terms.s4.p": "This site links to and embeds material from third parties (for example, map providers, font services). EEA is not responsible for the content of third-party websites.",
  "terms.s5.h2": "5. Acceptable Use",
  "terms.s5.p": "You agree not to use this website in any way that is unlawful, that infringes others' rights, that introduces malicious code, or that attempts unauthorised access to non-public areas.",
  "terms.s6.h2": "6. Governing Law",
  "terms.s6.p": "These Terms are governed by the law of the Hellenic Republic. Any dispute arising from your use of this site is subject to the exclusive jurisdiction of the courts of Athens.",
  "terms.s7.h2": "7. Contact",
  "terms.s7.p": "Questions about these terms? Email <strong>legal@eea.edu.gr</strong>.",

  "adm.notice.title": "📢 Autumn 2026 applications are open.",
  "adm.notice.dates": "Early-decision deadline: <strong>30 June 2026</strong> · Regular deadline: <strong>31 July 2026</strong> · Late round (if seats remain): <strong>05 September 2026</strong>.",
  "adm.apply.title": "How to Apply",
  "adm.apply.intro": "EEA admits students through a holistic review of academic achievement, two short essays, and a short online conversation with a faculty admissions reader. There is no entrance examination.",
  "adm.apply.step1": "<strong>Create an applicant account.</strong> Register at <em>apply.eea.edu.gr</em> with a valid email address.",
  "adm.apply.step2": "<strong>Submit the online application form.</strong> Includes personal details, education history, your two 500-word essays, and a programme preference.",
  "adm.apply.step3": "<strong>Upload supporting documents</strong> — see the <a href=\"#requirements\">Requirements</a> section below.",
  "adm.apply.step4": "<strong>Pay the €40 application fee</strong> (waived for applicants from Greece, Cyprus and the rest of the EU until 30 June 2026).",
  "adm.apply.step5": "<strong>Sit a 30-minute online conversation</strong> with one of our admissions readers. Available in Greek or English.",
  "adm.apply.step6": "<strong>Receive a decision</strong> within 3 weeks of completing your interview. Offers are conditional on final school-leaving results where applicable.",
  "adm.req.title": "Requirements",
  "adm.req.gr.title": "For Greek high-school applicants (Apolytirio)",
  "adm.req.gr.b1": "Apolytirio Lykeiou or expected to graduate in summer 2026",
  "adm.req.gr.b2": "Minimum overall grade of 16/20 (or 15/20 with strong subject-specific marks in mathematics and physics)",
  "adm.req.gr.b3": "Panhellenic Examination results are not required but, if available, may be submitted in support of the application",
  "adm.req.gr.b4": "One short essay in Greek and one in English (or both in English at the applicant's choice)",
  "adm.req.intl.title": "For EU and international applicants",
  "adm.req.intl.b1": "Upper secondary qualification recognised in your country (IB Diploma · A-Levels · Abitur · Lise Diploması · French Baccalauréat · etc.)",
  "adm.req.intl.b2": "Strong academic record in mathematics and at least one science subject",
  "adm.req.intl.b3": "English proficiency: IELTS 6.5+ / TOEFL iBT 90+ / Cambridge C1 / EEA proficiency interview waiver",
  "adm.req.intl.b4": "For Architecture &amp; Heritage applicants: a portfolio of 8–12 works (drawings, sketches, modelling, photography, design work)",
  "adm.req.docs.title": "Required documents",
  "adm.req.docs.b1": "Official transcripts from the last three years of secondary education",
  "adm.req.docs.b2": "Copy of national ID or passport biographic page",
  "adm.req.docs.b3": "Two letters of recommendation (one academic, one personal)",
  "adm.req.docs.b4": "Curriculum vitae / résumé (one page)",
  "adm.req.docs.b5": "Personal statement (500 words)",
  "adm.req.docs.b6": "Programme-specific essay (500 words)",
  "adm.tuition.title": "Tuition &amp; Fees (2026/27)",
  "adm.tuition.col1": "Programme",
  "adm.tuition.col2": "Greek / EU",
  "adm.tuition.col3": "International",
  "adm.tuition.r1c1": "B.Eng — Computer, Civil, Mechanical, Electrical, Environmental",
  "adm.tuition.r1c2": "€8,500 / year",
  "adm.tuition.r1c3": "€11,800 / year",
  "adm.tuition.r2c1": "B.Arch + M.Arch — Architecture &amp; Heritage (5-year integrated)",
  "adm.tuition.r2c2": "€9,200 / year",
  "adm.tuition.r2c3": "€12,500 / year",
  "adm.tuition.r3c1": "M.Sc / M.Eng (all four programmes)",
  "adm.tuition.r3c2": "€11,500 (full)",
  "adm.tuition.r3c3": "€14,800 (full)",
  "adm.tuition.r4c1": "Application fee",
  "adm.tuition.r4c2": "€40 (waived through 30 Jun 2026)",
  "adm.tuition.r4c3": "€40",
  "adm.tuition.r5c1": "Student services fee (annual)",
  "adm.tuition.r5c2": "€200",
  "adm.tuition.r5c3": "€200",
  "adm.tuition.r6c1": "Health &amp; insurance fee (annual)",
  "adm.tuition.r6c2": "€180",
  "adm.tuition.r6c3": "€350",
  "adm.tuition.note": "Tuition may be paid in two equal instalments (October and February). EEA participates in the Hellenic Education Loan Programme operated by the National Bank of Greece, which offers loans up to €15,000/year with deferred repayment.",
  "adm.schol.title": "Scholarships &amp; Financial Aid",
  "adm.schol.b1": "<strong>Founder's Scholarship</strong> — 50 awards for the 2026 intake, covering 30 % – 70 % of tuition. Awarded on academic merit alone. Application deadline: 30 June 2026.",
  "adm.schol.b2": "<strong>Diaspora Scholarship</strong> — Reserved for students of Greek heritage holding a non-Greek passport. Covers 25 % of tuition for the full programme. 15 awards / year.",
  "adm.schol.b3": "<strong>Hephaestus Industry Sponsorships</strong> — Six full-tuition sponsorships per year, jointly funded by our industry partner network, with a guaranteed paid summer internship between Years 2 and 3.",
  "adm.schol.b4": "<strong>Pythia Women-in-Engineering Award</strong> — 10 awards per year covering 40 % of tuition, for women entering the Computer, Mechanical or Electrical programmes.",
  "adm.schol.b5": "<strong>Need-Based Bursaries</strong> — A separate bursary fund of €120,000 per year is reserved for students whose household income falls below national thresholds.",
  "adm.intl.title": "International Students",
  "adm.intl.intro": "EEA welcomes applications from students worldwide. We host a dedicated International Student Office that supports admitted students with visas, residence permits, accommodation, and onboarding.",
  "adm.intl.visa.title": "Visa &amp; Residence",
  "adm.intl.visa.body": "Non-EU applicants offered a place will receive a formal letter of acceptance which can be presented to a Greek consular post for a national (D) student visa. Upon arrival in Greece, students apply for a residence permit for study (valid for the full duration of the programme) at the Aliens &amp; Immigration Directorate of Attica.",
  "adm.intl.accom.title": "Accommodation",
  "adm.intl.accom.body": "Until our on-campus residence opens (autumn 2027), the Office partners with three serviced student-housing operators in Peania, Paiania, Glyka Nera and Spata — all within a 10-minute commute of the campus. Estimated cost: €380 – €650 / month including utilities.",
  "adm.intl.cost.title": "Cost of Living in Athens / Peania",
  "adm.intl.cost.b1": "Rent (shared apartment): €380 – €650 / month",
  "adm.intl.cost.b2": "Groceries: €220 – €320 / month",
  "adm.intl.cost.b3": "Public transport monthly pass (Athens area): €27 (student rate €13.50)",
  "adm.intl.cost.b4": "Mobile data plan: €10 – €20 / month",
  "adm.intl.cost.b5": "Total recommended budget: €750 – €1,100 / month",
  "adm.faq.title": "Frequently Asked Questions",
  "adm.faq.q1": "Is EEA's degree recognised in Greece and the EU?",
  "adm.faq.a1": "Yes. EEA delivers degree programmes under formal academic affiliation with established European universities. The degree certificate is issued by the partner university and is fully recognised within Greece via DOATAP and across the European Higher Education Area under the Bologna framework.",
  "adm.faq.q2": "Do I need to know Greek to study at EEA?",
  "adm.faq.a2": "No. All engineering programmes are delivered in English. We do offer free Greek-language classes (A1 through B2 levels) to all international students because life in Peania is much easier with some Greek, and many internships in Greek industry will benefit from it.",
  "adm.faq.q3": "Can I transfer credits from another university?",
  "adm.faq.a3": "Yes. Transfer applications are reviewed individually by the receiving department. Up to 60 ECTS may be transferred for an undergraduate programme; the final two years must be completed at EEA.",
  "adm.faq.q4": "Are there entrance exams?",
  "adm.faq.a4": "No. EEA uses holistic admission. We assess academic record, essays and a 30-minute online conversation with a faculty reader.",
  "adm.faq.q5": "When will I hear back?",
  "adm.faq.a5": "Decisions are released within three weeks of a complete application file (including the interview). The latest decision date for the early-decision round is 21 July 2026.",
  "adm.faq.q6": "What happens if I'm placed on the waitlist?",
  "adm.faq.a6": "Waitlisted candidates remain in consideration until 5 September 2026. Most movement off the waitlist happens between 25 July and 20 August, after offer-holders confirm their places.",
  "adm.side.dates": "Key Dates 2026",
  "adm.side.dates.d1": "<strong>Early deadline:</strong> 30 Jun",
  "adm.side.dates.d2": "<strong>Regular deadline:</strong> 31 Jul",
  "adm.side.dates.d3": "<strong>Late round:</strong> 05 Sep",
  "adm.side.dates.d4": "<strong>Orientation:</strong> 21–25 Sep",
  "adm.side.dates.d5": "<strong>Lectures begin:</strong> 28 Sep",
  "adm.side.links": "Quick Links",
  "adm.side.l1": "How to Apply",
  "adm.side.l2": "Requirements",
  "adm.side.l3": "Tuition &amp; Fees",
  "adm.side.l4": "Scholarships",
  "adm.side.l5": "International",
  "adm.side.l6": "FAQ",
  "adm.side.cta1": "Begin Application",
  "adm.side.cta2": "Ask a Question"
};
